format_version: 3
pipelines:
  Test-REPO77-release:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      Test-REPO77:
        git: https://github.com/siddhi1907/Test-REPO77.git
        shallow_clone: false
        auto_update: true
        branch: master
    parameters:
      BRANCH: master
      VERSION: '1.0'
    template: testing-pipelines-1.2
